@baseUrl = http://localhost:3000
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQzLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJ0ZW5hbnRJZCI6bnVsbCwiaWF0IjoxNzc1MjMwODM5LCJleHAiOjE3NzUyMzQ0Mzl9.48Iw-tbkE9MvOJq0To5ZIlGRKhAdPjZVbP2IJ8eedS8

### Register (invite token from POST /tenants/:tenantId/invites)
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "michael.scott@example.com",
  "password": "password",
  "firstName": "Michael",
  "lastName": "Scott",
  "token": "9b78ac8699963cf68b8e127b6a922d163c3dd07c50d1b739d4fcc671df4bf0b1"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "password",
  "slug": "admin"
}

### Refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "2bb1b2e1343879a504c29f97ab132c7fb80fe322ae95462b3130243d400fc5ca"
}

### Logout (invalidate single refresh token)
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "c64a74ac69972e4cff2261204ea2e4a96baf8985ea40ae05cf0bdcf3b172089d"
}

### Logout all sessions
POST {{baseUrl}}/auth/logout-all
Authorization: Bearer {{accessToken}}
