@baseUrl = http://localhost:3000
@contentType = application/json

### Create invite
POST {{baseUrl}}/invites
Content-Type: {{contentType}}

{
  "email": "john.doe@example.com",
  "tenantId": 2,
  "roleId": 1
}
