@baseUrl = http://localhost:3000
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQzLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJ0ZW5hbnRJZCI6bnVsbCwiaWF0IjoxNzc1MjMwODM5LCJleHAiOjE3NzUyMzQ0Mzl9.48Iw-tbkE9MvOJq0To5ZIlGRKhAdPjZVbP2IJ8eedS8

### Create tenant
POST {{baseUrl}}/tenants
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "name": "BioPulse Labs",
  "slug": "biopulse",
  "address": "123 Main St, New York, NY 10001, USA"
}

### Create tenant (minimal)
POST {{baseUrl}}/tenants
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "name": "Minimal Tenant",
  "slug": "minimal-tenant"
}

### Get tenant by id
GET {{baseUrl}}/tenants/9
Authorization: Bearer {{accessToken}}


### Update tenant
PUT {{baseUrl}}/tenants/1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "name": "Acme Corp Updated",
  "slug": "acme-corp-updated",
  "address": "456 Oak Ave"
}

### Update tenant (partial)
PUT {{baseUrl}}/tenants/1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "address": null
}

### Delete tenant
DELETE {{baseUrl}}/tenants/1
