@baseUrl = http://localhost:3000
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJ1c2VyIl0sInN1YiI6MzEsImp0aSI6IjE3NzE0NDM5NDk4MDAiLCJpYXQiOjE3NzE0NDM5NDksImV4cCI6MTc3MTQ0NzU0OX0.4CXunkL_U6wLdX4ZmkXYSKhuVQ9toNtiSbrJykW1l2w

### Create user
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "P@ssw0rd",
  "firstName": "Jane",
  "lastName": "Doe"
}

### Get user by id
GET {{baseUrl}}/users/1

### Update user
PUT {{baseUrl}}/users/17
Content-Type: {{contentType}}

{
  "firstName": "John",
  "lastName": "Smith"
}

### Update user roles
PUT {{baseUrl}}/users/27/roles
Content-Type: {{contentType}}

{
  "roles": ["client", "specialist"]
}

### Delete user
DELETE {{baseUrl}}/users/17
