@baseUrl = http://localhost:3000
@contentType = application/json

### Create user
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "P@ssw0rd",
  "firstName": "Jane",
  "lastName": "Doe"
}

### Sign in
POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password": "P@ssw0rd"
}

### Refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "195d1a6e4178f9a3723a08b4652f7c79ecfd935d969d0719920baa66c8888598"
}

### Get user by id
GET {{baseUrl}}/users/1

### Update user
PUT {{baseUrl}}/users/17
Content-Type: {{contentType}}

{
  "firstName": "John",
  "lastName": "Smith"
}

### Update user roles
PUT {{baseUrl}}/users/27/roles
Content-Type: {{contentType}}

{
  "roles": ["client", "specialist"]
}

### Delete user
DELETE {{baseUrl}}/users/17
